### ISSUE TITLE
Saved ply has no color

### ISSUE THREAD

**Issue by Xieyifei1229** [STORM-IRIT/pcednet-supp#11]
Hello author, I would like to ask how to save the extracted feature point cloud. The point cloud obtained after clicking Save Classification is the original point cloud. Could you please answer my question? Thank you

**Comment by nmellado** [comment]
Dear @Xieyifei1229,

Could you please open one of the generated ply file with a text editor, and paste the content of the ply header here ?

**Comment by Xieyifei1229** [comment]
thanks, hold on please.
This is the ply header that I got.
ply
format ascii 1.0
comment Generated by Eignet using PCA lib
comment Written with hapPLY (https://github.com/nmwsharp/happly)
element vertex 11932
property float x
property float y
property float z
end_header

I find here says color and normal information but can‘t find in ply header.
![图片](https://user-images.githubusercontent.com/56998683/227447411-02605d68-c110-44e6-b320-d5f7876206ca.png)
![图片](https://user-images.githubusercontent.com/56998683/227447494-7228d7ab-1306-446b-b25b-dadadfd2211c.png)

**Comment by nmellado** [comment]
Ok thanks, and you confirm that you clicked on the button `Save Classification` to obtain this file ?
In that case, coud you post here details about your operating system please ?

**Comment by Xieyifei1229** [comment]
Yes, I am sure that I clicked on the button Save Classification.
My operating system is Windows 10. Here is the information:

Version Windows 10 Professional Workstation Edition
Version No. 21H2
Installation date 2022/5/20
Operating system build 19044.1526
Experience Windows Feature Experience Pack 120.2212.4170.0

**Comment by nmellado** [comment]
Ok thank you for the report, we will investigate this issue ASAP.

**Comment by Xieyifei1229** [comment]
Thank you! I will pay attention to this issue.
Could you please answer me when the issue is resolved?

**Comment by nmellado** [comment]
Hi,
We found the bug, there is an issue when saving the file indeed.
We are working on patching the code, I'll update the issue after uploading the binaries.

Thanks for your report.

**Comment by nmellado** [comment]
Should be fixed by v1.0.1, please re-open if not.

Thanks for your report !
