### ISSUE TITLE
How to deal with batch models all at once?

### ISSUE THREAD

**Issue by Mffff666** [STORM-IRIT/pcednet-supp#12]
Hello, author. Good work for your team.

I find that the standalone demo can only work for a single model once a time. Is there other interface that is provided for batch models processing?

Appreciate to your reply.

**Comment by nmellado** [comment]
Dear @Mffff666,
Batch processing is not part of the demo.
If you need this feature, please contact me by email so we can see how to process your data (depending on your use case: research of industrial applications).
Best
Nicolas
