### ISSUE TITLE
When will the model be accessed?

### ISSUE THREAD

**Issue by Babylonehy** [STORM-IRIT/pcednet-supp#4]
as mentioned above.

**Comment by nmellado** [comment]
We can share pre-compiled binaries, please contact me by email for more details.

**Comment by nmellado** [comment]
Binaries and pre-trained models will be made available here: https://storm-irit.github.io/pcednet-supp/software.html

**Comment by nmellado** [comment]
Now available at https://storm-irit.github.io/pcednet-supp/software.html
Video describing how to use: #7
